# Generated by Django 2.2.16 on 2022-08-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
